// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVZLLTjtc9aY8XWVjcma1WIN9_g3oOmv4',
    appId: '1:561131500307:web:b541a1362ef793f2f720e6',
    messagingSenderId: '561131500307',
    projectId: 'budgeting-app-28bb6',
    authDomain: 'budgeting-app-28bb6.firebaseapp.com',
    storageBucket: 'budgeting-app-28bb6.firebasestorage.app',
    measurementId: 'G-W1XHCWGLML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAobywZ7J6zCQJMLCP_KshaOOZGv1QKWNg',
    appId: '1:561131500307:android:a24d8b81bafcdb1af720e6',
    messagingSenderId: '561131500307',
    projectId: 'budgeting-app-28bb6',
    storageBucket: 'budgeting-app-28bb6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIEeJxlFleSbc72JBY1dSMGEkmhZsWIt4',
    appId: '1:561131500307:ios:20ff898612b2e07bf720e6',
    messagingSenderId: '561131500307',
    projectId: 'budgeting-app-28bb6',
    storageBucket: 'budgeting-app-28bb6.firebasestorage.app',
    iosBundleId: 'com.example.budgettingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIEeJxlFleSbc72JBY1dSMGEkmhZsWIt4',
    appId: '1:561131500307:ios:20ff898612b2e07bf720e6',
    messagingSenderId: '561131500307',
    projectId: 'budgeting-app-28bb6',
    storageBucket: 'budgeting-app-28bb6.firebasestorage.app',
    iosBundleId: 'com.example.budgettingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVZLLTjtc9aY8XWVjcma1WIN9_g3oOmv4',
    appId: '1:561131500307:web:fe2e6eacdc708e62f720e6',
    messagingSenderId: '561131500307',
    projectId: 'budgeting-app-28bb6',
    authDomain: 'budgeting-app-28bb6.firebaseapp.com',
    storageBucket: 'budgeting-app-28bb6.firebasestorage.app',
    measurementId: 'G-JTE30SFN14',
  );
}
